IgnorePath '/boot/*.img'
IgnorePath '/boot/BOOT'
IgnorePath '/boot/EFI'
IgnorePath '/boot/System Volume Information'
IgnorePath '/boot/vmlin*'

IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/.updated'
IgnorePath '/etc/NetworkManager/system-connections/*'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/brlapi.key'
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/fstab'
IgnorePath '/etc/hostname'
IgnorePath '/etc/hosts'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/localtime'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/os-release'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/shells'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/udev/hwdb.bin'
IgnorePath '/etc/xml/catalog'

IgnorePath '/etc/systemd/system/getty.target.wants/getty@tty1.service'
IgnorePath '/etc/systemd/system/multi-user.target.wants/remote-fs.target'
IgnorePath '/etc/systemd/user/sockets.target.wants/dirmngr.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/gpg-agent-extra.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/gpg-agent-ssh.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/gpg-agent.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/p11-kit-server.socket'

IgnorePath '/etc/group'
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/passwd.OLD'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'

IgnorePath '/lost+found'

IgnorePath '/usr/bin/__pycache__/*'
IgnorePath '/usr/lib/gdk-pixbuf-*/**/loaders.cache'
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/lib/gtk-*/**/immodules.cache'
IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/modules/*'
IgnorePath '/usr/lib/python2.7/**.pyc'
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/fonts/*'
IgnorePath '/usr/share/glib-*/schemas/gschemas.compiled'
IgnorePath '/usr/share/icons/**/icon-theme.cache'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/nvim/runtime/.netrwhist'

IgnorePath '/var/.updated'
IgnorePath '/var/db/*'
IgnorePath '/var/lib/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
