#!/bin/sh

ARGS=("$@")
DOTFILES=$PWD

if [[ " ${ARGS[@]} " =~ " --skip-save " ]]; then
  aconfmgr save
fi

if [[ ! " ${ARGS[@]} " =~ " --force " ]]; then
  if [ -n "$(git status -s)" ]; then
    echo "The dotfiles repository contains local changes."
    exit 1
  fi
fi

git fetch
if [[ ! " ${ARGS[@]} " =~ " --force " ]]; then
  if [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) ]]; then
    echo "The local configuration is up to date."
    exit 0
  fi
fi

git merge FETCH_HEAD
aconfmgr apply

cd $DOTFILES/user    && ./install
cd $DOTFILES/private && ./install

if [[ " ${ARGS[@]} " =~ " --dconf " ]]; then
  cd $DOTFILES/dconf && ./install
fi
