#!/bin/sh

DOTFILES=$PWD

aconfmgr save
if [ -n "$(git status -s)" ]; then
  echo "The dotfiles repository contains local changes."
  exit 1
fi

git pull
# TODO: git pull - check if there are changes, or force
aconfmgr apply

cd $DOTFILES/user    && ./install
cd $DOTFILES/private && ./install

if [ "$1" == "--dconf" ]; then
  cd $DOTFILES/dconf && ./install
fi
