#!/bin/sh

if xrandr | grep -q '^DP1 connected'; then
    # Reduce resolution of laptop monitor (larger text), place the external monitor above:
    xrandr --output eDP1 --mode 3200x1800 --output DP1 --auto --above eDP1

    # Invert Win and Alt (for external keyboard):
    setxkbmap -option altwin:swap_lalt_lwin
fi
