#!/bin/sh

setup() {
    if xrandr | grep -q '^DP1 connected'; then
        # Reduce resolution of laptop monitor (larger text), place the external monitor above:
        xrandr --output eDP1 --mode 3200x1800 --output DP1 --auto --above eDP1
    else
        return 1
    fi

    setxkbmap -option ctrl:nocaps               # CapsLock (keep pressed)    => Ctrl
    killall xcape; xcape -e "Control_L=Escape"  # Ctrl/CapsLock (press once) => Escape

    return 0
}

# Try twice (useful if the monitor is getting out of sleep mode).
# If it fails both times, just assume the monitor was disconnected.
setup; sleep 5; setup || undesk
