#!/bin/sh

setup() {
    if xrandr | grep -q '^DP1 connected'; then
        xrandr --output eDP1 --mode 3200x1800 --pos 1320x2160 --output DP1 --auto --scale 1.5x1.5 --pos 0x0
        ret=0
    else
        ret=1
    fi

    setxkbmap -option ctrl:nocaps               # CapsLock (keep pressed)    => Ctrl
    killall xcape; xcape -e "Control_L=Escape"  # Ctrl/CapsLock (press once) => Escape

    return $ret
}

# Try twice (useful if the monitor is getting out of sleep mode).
# If it fails both times, just assume the monitor was disconnected.
setup; sleep 5; setup || undesk
