#!/bin/sh

getWorkspaceInfo() {
    WS=$(i3-msg -t 'get_workspaces' | sed -e 's/{"num/\n{"num/g' | grep \"focused\":true | sed -e 's/,"/\n/g' | grep name | cut -d\" -f 3)
    WS_TEXT=$(echo $WS | cut -d \: -f 2)
    WS_NUM=$(echo $WS | cut -d \: -f 1)
}

getWorkspaceInfo
i3-input -F "rename workspace to \"$WS_NUM:%s\"" -P 'New name: ' -f 'pango:SauceCodePro Nerd Font 24'

getWorkspaceInfo
[ -z "$WS_TEXT" ] && i3-msg "rename workspace to \"$WS_NUM\""
