#!/bin/sh

MV=-110
alias undervolt=/home/andrea/src/undervolt/undervolt.py

if [ $# == 1 ]; then
  if [ "$1" == "-r" ]; then
    undervolt --read
    exit
  else
    MV=$1
  fi
fi

undervolt --core $MV --gpu $MV --cache $MV --uncore $MV --analogio $MV
