#!/bin/sh

MV=-110

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
alias undervolt="$SCRIPTPATH/undervolt-git/undervolt.py"

if [ $# == 1 ]; then
  if [ "$1" == "-r" ]; then
    undervolt --read
    exit
  else
    MV=$1
  fi
fi

undervolt --core $MV --gpu $MV --cache $MV --uncore $MV --analogio $MV
