IgnorePath '/boot/EFI'
IgnorePath '/boot/*.img'
IgnorePath '/boot/vmlin*'

IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/.updated'
IgnorePath '/etc/NetworkManager/system-connections'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/brlapi.key'
IgnorePath '/etc/ca-certificates/extracted'
IgnorePath '/etc/fstab'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/os-release'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/rabbitmq/rabbitmq-env.conf'
IgnorePath '/etc/shells'
IgnorePath '/etc/ssl/certs'

IgnorePath '/etc/group'
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/passwd.OLD'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'

IgnorePath '/lost+found'

IgnorePath '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/lib/gtk-2.0/2.10.0/immodules.cache'
IgnorePath '/usr/lib/gtk-3.0/3.0.0/immodules.cache'
IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/modules/*'
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/fonts/*'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled'
IgnorePath '/usr/share/icons/*'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/nvim/runtime/.netrwhist'

IgnorePath '/var/.updated'
IgnorePath '/var/db/*'
IgnorePath '/var/lib/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
