#!/bin/sh

ln -vsf $PWD/bin ~/
ln -vsf $PWD/.gitconfig ~/
ln -vsf $PWD/.spacemacs.d ~/
ln -vsf $PWD/.xinitrc ~/
ln -vsf $PWD/.zprofile ~/

mkdir -p ~/.config
ln -vsf $PWD/.config/awesome ~/.config/
ln -vsf $PWD/../aconfmgr ~/.config/
